# Block radius to consider nearby mobs for stacking
stack-radius: 16

# Radius in blocks within which a player must be present to activate stacking
player-radius: 50

# Maximum size of a mob stack
max-stack-size: 9999

# Block radius to consider nearby items for stacking
item-stack-radius: 5

# Maximum size of an item stack
max-item-stack-size: 9999

# Stacks naturally spawning mobs
stack-natural-mobs: true

# Stacks mobs that spawn from spawners
stack-spawner-mobs: true

# Stack items on the ground
stack-items: true

# Enable cross-stack absorption (mobstacks merge together)
enable-stack-absorption: true

# Types of mobs that can be stacked
stackable-types:
    - "ZOMBIE"
    - "SKELETON"
    - "CREEPER"
    - "SPIDER"
    - "CAVE_SPIDER"
    - "ENDERMAN"
    - "WITCH"
    - "SLIME"
    - "MAGMA_CUBE"
    - "BLAZE"
    - "GHAST"
    - "COW"
    - "SHEEP"
    - "PIG"
    - "CHICKEN"
    - "RABBIT"
    - "HORSE"
    - "DONKEY"
    - "MULE"
    - "LLAMA"
    - "VILLAGER"